<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HotelBooking.Api\HotelBooking.Api.csproj" />
    <ProjectReference Include="..\..\src\HotelBooking.Contracts\HotelBooking.Contracts.csproj" />
    <ProjectReference Include="..\..\src\HotelBooking.Core\HotelBooking.Core.csproj" />
    <ProjectReference Include="..\..\src\HotelBooking.Infrastructure\HotelBooking.Infrastructure.csproj" />
  </ItemGroup>

</Project>