<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>a5b4df1e-234e-422e-aa57-8bba4d54576f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelBooking.Contracts\HotelBooking.Contracts.csproj" />
    <ProjectReference Include="..\HotelBooking.Core\HotelBooking.Core.csproj" />
    <ProjectReference Include="..\HotelBooking.Infrastructure\HotelBooking.Infrastructure.csproj" />
  </ItemGroup>

</Project>
