<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelBooking.Contracts\HotelBooking.Contracts.csproj" />
    <ProjectReference Include="..\HotelBooking.Core\HotelBooking.Core.csproj" />
    <ProjectReference Include="..\HotelBooking.Infrastructure\HotelBooking.Infrastructure.csproj" />
  </ItemGroup>

</Project>
